# Generated by Django 6.0.7 on 2026-07-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("sku", models.CharField(max_length=50, unique=True)),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("category", models.CharField(blank=True, max_length=80)),
                ("reorder_level", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
